export const DOG_BREEDS = [
  "Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "Bulldog",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "Yorkshire Terrier",
  "Boxer",
  "Dachshund",
  "Siberian Husky",
  "Chihuahua",
  "Border Collie",
  "Shiba Inu",
  "Doberman Pinscher",
  "Australian Shepherd",
  "Great Dane",
  "Corgi",
  "Pomeranian",
  "Maltese",
];

export const CAT_BREEDS = [
  "Domestic Shorthair",
  "Domestic Longhair",
  "Siamese",
  "Persian",
  "Maine Coon",
  "Ragdoll",
  "Bengal",
  "Sphynx",
  "British Shorthair",
  "Abyssinian",
  "Scottish Fold",
  "Savannah",
  "Norwegian Forest",
  "Russian Blue",
  "Birman",
];
